version: '3.8'

services:
  dashboard:
    build: .
    container_name: squid-dashboard
    restart: always
    ports:
      - "1080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - DEBUG=True
