# Generated by Django 6.0.5 on 2026-05-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('rule_type', models.CharField(choices=[('block', 'Blacklist'), ('allow', 'Whitelist'), ('hide', 'Oculto')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HiddenDomain',
        ),
    ]
