# Generated by Django 6.0.5 on 2026-05-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_domainrule_delete_hiddendomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainrule',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domainrule',
            name='rule_type',
            field=models.CharField(choices=[('none', 'Nenhuma'), ('block', 'Blacklist'), ('allow', 'Whitelist'), ('hide', 'Oculto')], default='none', max_length=10),
        ),
    ]
